#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# aide-common
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'AIDE - Advanced Intrusion Detection Environment'
group 'pkgs'
label 'sec'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
aide-common::check() { dpkg -l | grep aide-common 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
aide-common::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install aide-common &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
aide-common::config()
{
	local result service timer

    if ! grep -R -E '^!/var/lib/lxcfs/cgroup$' /etc/aide/*; then
        sudo sh -c "echo \"!/var/lib/lxcfs/cgroup\" > /etc/aide/aide.conf.d/70_aide_lxcfs"
    fi

    if ! grep -R -E '^!/var/lib/docker$' /etc/aide/*; then
        sudo sh -c "echo '!/var/lib/docker' > /etc/aide/aide.conf.d/70_aide_docker"
    fi

    sudo sed -i 's/^Checksums.*/Checksums = sha512/' /etc/aide/aide.conf

    echoDot "OK" -c "${LT_GREEN}"

    echoDot "Running Aide (this might take a while) - " -s "\t▷" -n

    aideinit --yes; result=$?

    if [[ "$result" -eq 0 ]]; then
        log::info "Successfully ran Aide"
        echoAlias "OK" -c "${LT_GREEN}"
    else
        log::error "Failed to run Aide"
        echoAlias "FAILED!" -c "${RED}"
    fi

    echoDot "Enable daily Aide check - " -s "\t▷" -n

    if [ -f "$CUSTOM/cfg/aide/aidecheck.service" ]; then
        service="$CUSTOM/cfg/aide/aidecheck.service"
    elif [ -f "$DOT_CFG/aide/aidecheck.service" ]; then
        service="$DOT_CFG/aide/aidecheck.service"
    else
        exitLog "Data file '$DOT_CFG/aide/aidecheck.service' not found"
    fi
    if [ -f "$CUSTOM/cfg/aide/aidecheck.timer" ]; then
        timer="$CUSTOM/cfg/aide/aidecheck.timer"
    elif [ -f "$DOT_CFG/aide/aidecheck.timer" ]; then
        timer="$DOT_CFG/aide/aidecheck.timer"
    else
        exitLog "Data file '$DOT_CFG/aide/aidecheck.timer' not found"
    fi

    sudo install -v -b -m 0644 -C -D -t /etc/systemd/system "$service"
    sudo install -v -b -m 0644 -C -D -t /etc/systemd/system "$timer"

    sudo systemctl reenable aidecheck.timer
    sudo systemctl restart aidecheck.timer
    sudo systemctl daemon-reload; result=$?

    if [[ $VERBOSE == "Y" ]]; then
        sudo systemctl status aidecheck.timer --no-pager
        echo
    fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
aide-common::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge aide-common &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
