#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# ansible
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
ansible::check() { dpkg -l | grep ansible 2> /dev/null 1>&2; return $?; }
# ------------------------------------------------------------------
# INSTALL
# ------------------------------------------------------------------
ansible::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install ansible &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
# ------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------
ansible::config()
{
	echo ""
}
# ------------------------------------------------------------------
# REMOVE
# ------------------------------------------------------------------
ansible::remove()
{
	local result

    sudo apt-get -qq -y purge ansible &> /dev/null; result=$?
    if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
