#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# apparmor
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'AppArmor - Linux kernel security module used to restrict the capabilities of apps'
group 'pkgs'

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
apparmor::check() { dpkg -l | grep libpam-apparmor 2> /dev/null 1>&2; return $?; }
# ------------------------------------------------------------------
# INSTALL
# ------------------------------------------------------------------
apparmor::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install apparmor-profiles apparmor-utils libpam-apparmor &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
# ------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------
apparmor::config()
{
	local result

    if ! grep 'session.*pam_apparmor.so order=user,group,default' /etc/pam.d/*; then
        sudo sh -c "echo 'session optional pam_apparmor.so order=user,group,default' > /etc/pam.d/apparmor"
    fi

    if ! grep -q 'apparmor=1' /proc/cmdline; then
        # shellcheck disable=SC2016
        sudo sh -c "echo 'GRUB_CMDLINE_LINUX=\"\$GRUB_CMDLINE_LINUX apparmor=1 security=apparmor\"' > /etc/default/grub.d/99-hardening-apparmor.cfg"
    fi

    sudo systemctl enable apparmor.service
    sudo systemctl restart apparmor.service; result=$?

    find /etc/apparmor.d/ -maxdepth 1 -type f -exec aa-enforce {} \;

    if [[ $VERBOSE == "Y" ]]; then
        sudo systemctl status apparmor.service --no-pager
        echo
    fi

	return $result
}
# ------------------------------------------------------------------
# REMOVE
# ------------------------------------------------------------------
apparmor::remove()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y purge apparmor-profiles apparmor-utils libpam-apparmor &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
