#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# apt
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'APT - Advanced Package Tool'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
apt::check() { if dpkg -l | grep apt-transport-https 2> /dev/null 1>&2 && dpkg -l | grep apt-listchanges 2> /dev/null 1>&2; then return 0; else return 1; fi }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
apt::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install apt-transport-https apt-listchanges &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
apt::config()
{
	local result=0

	if [ ! -f /etc/apt/apt.conf.d/99forve-ipv4 ]; then
		sudo sh -c "printf -- '%s' 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"; result=$?
	fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
apt::remove()
{
	local result

	sudo rm -f /etc/apt/apt.conf.d/99force-ipv4 &> /dev/null
	sudo apt-get -qq -y purge apt-transport-https apt-listchanges &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
