#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# bash-completion
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'BASH Completion - Programmable command completion'
group 'pkgs'
label 'feat'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
bash-completion::check() { dpkg -l | grep bash-completion 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
bash-completion::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install bash-completion &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
bash-completion::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge bash-completion &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
