#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# bind9-dnsutils
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'DNS client programs derived from the BIND9 source tree'
group 'pkgs'
label 'service'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
bind9-dnsutils::check() { dpkg -l | grep bind9-dnsutils 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
bind9-dnsutils::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install bind9-dnsutils; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean && sudo apt-get -qq -y autoremove; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
bind9-dnsutils::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge bind9-dnsutils; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean && sudo apt-get -qq -y autoremove; fi

	return $result
}
