#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# chkrootkit
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Chkrootkit - Checks the target system for signs it has been tampered with'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
chkrootkit::check() { dpkg -l | grep chkrootkit 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
chkrootkit::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install chkrootkit &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
chkrootkit::remove()
{
	local result

	  sudo apt-get -qq -y purge chkrootkit &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
