#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# cockpit
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Cockpit - Web-Based GUI for Servers'
group 'pkgs'
label 'gui'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
cockpit::check() { dpkg -l | grep cockpit 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
cockpit::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install cockpit &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
cockpit::config()
{
	local result

	sudo systemctl enable --now cockpit.socket
	sudo systemctl cockpit.socket; result=$?

	return $result
}
#-------------------------------------------------------------------
# POST CONFIG
#-------------------------------------------------------------------
cockpit::post_config()
{
	echo ""
	echoDot "Interface @ http://localhost:9090" -s "★" -c "${GOLD}"
	echo ""
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
cockpit::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge cockpit &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
