#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# cracklib-runtime
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
cracklib-runtime::check() { dpkg -l | grep cracklib-runtime 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
cracklib-runtime::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install cracklib-runtime &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
cracklib-runtime::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge cracklib-runtime &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
