#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# cron-updates
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Custom APT update script set to run automatically every day'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
cron-updates::check() { sudo find /etc/cron.daily -type f -name 'apt-update' &> /dev/null; return $?;  }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
cron-updates::install()
{
	local result

	sudo install -v -b -m 0755 -C -D -t /etc/cron.daily "$DOT_CFG/cron/apt-update"; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
cron-updates::remove()
{
	local result

	rm -f /etc/cron.daily/apt-update; result=$?

	return $result
}
