#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# debsums
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'Check the MD5 sums of installed packages'
group 'pkgs'

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
debsums::check() { dpkg -l | grep debsums 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
debsums::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install debsums &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
debsums::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge debsums &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
