#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# dialog
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
dialog::check() { dpkg -l | grep dialog 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
dialog::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install dialog &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
dialog::config()
{
	local result gc="${1:-}"

	if [ -f "$DOT_CFG/.dialogrc" ]; then
		install -v -b -C -D -t "$HOME" "$DOT_CFG/.dialogrc"; result="$?"
	else
		result=1
	fi
	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
dialog::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge dialog &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
