#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# dos2unix
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
dos2unix::check() { dpkg -l | grep dos2unix 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
dos2unix::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install dos2unix &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
dos2unix::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge dos2unix &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
