#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# fail2ban
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Fail2Ban - Intrusion Detection & Prevention'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
fail2ban::check() { dpkg -l | grep fail2ban 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
fail2ban::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install fail2ban &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
fail2ban::config()
{
	local result source

    if [ -f "$CUSTOM/etc/fail2ban/jail.local" ]; then
        source="$CUSTOM/etc/fail2ban/jail.local"
    elif [ -f "$DOT_ETC/fail2ban/jail.local" ]; then
        source="$DOT_ETC/fail2ban/jail.local"
    else
        exitLog "Data file '$DOT_ETC/fail2ban/jail.local' not found"
    fi

	sudo install -v -b -m 0644 -C -D -t /etc/fail2ban/jail.local "$source"; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
fail2ban::remove()
{
	local result

	  sudo apt-get -qq -y purge fail2ban &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
