#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# gnupg
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'The GNU Privacy Guard - Provides digital encryption, signing services, key management & more ...'
group 'pkgs'
label 'security'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
gnupg::check() { dpkg -l | grep gnupg 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
gnupg::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install gpg gnupg gpg-agent pinentry-tty &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
gnupg::config()
{
    if [ -f "$CUSTOM/cfg/gnupg/gpg.conf" ]; then
        source="$CUSTOM/cfg/gnupg/gpg.conf"
    else
        source="$DOT_CFG/gnupg/gpg.conf"
    fi

    if [ -f "$source" ]; then
        install -b -C -m 0644 "$source" "$HOME/.gnupg/gpg.conf"
    fi

    if [ -f "$CUSTOM/cfg/gnupg/gpg-agent.conf" ]; then
        source="$CUSTOM/cfg/gnupg/gpg-agent.conf"
    else
        source="$DOT_CFG/gnupg/gpg-agent.conf"
    fi

    if [ -f "$source" ]; then
        install -b -C -m 0644 "$source" "$HOME/.gnupg/gpg-agent.conf"
    fi

    gpg-connect-agent reloadagent /bye &> /dev/null

	return 0
}
#-------------------------------------------------------------------
# POST CONFIG
#-------------------------------------------------------------------
gnupg::post_config()
{
	echoHead "Set 'pinentry-tty' as default pinentry program"

	sudo update-alternatives --config pinentry

	echo ""
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
gnupg::remove()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y purge gpg gnupg gpg-agent pinentry-tty &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
