#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# intellij-community
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'IntelliJ-Community - A top ranking, cross-platform IDE by Jetbrains'
group 'pkgs'
label 'development'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
intellij-community::check() { sudo find /opt -type d -name 'idea-IC-*' &> /dev/null; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
intellij-community::install()
{
    dot::include "alias.functions"

	local result path optPath dir

    [ "${#SEARCH_DOWNLOAD[@]}" -lt 2 ] && errorExit "Array mismatch ${SEARCH_DOWNLOAD[*]}"

    for dir in "${SEARCH_DOWNLOAD[@]}"
    do
        if [ -d "$dir" ]; then
            if find "$dir" -type f | grep -q "ideaIC-"; then
                # shellcheck disable=SC2012
                path="$(find "$dir" -name 'ideaIC-*' | head -n 1)"
                break
            fi
        fi
    done

    if [ -z "$path" ]; then
        wget -P "$HOME/Downloads" https://download-cdn.jetbrains.com/idea/ideaIC-2024.2.1.tar.gz &> /dev/null
        path="$(find "$HOME/Downloads" -name 'ideaIC-*' | head -n 1)"
    fi

    chmod 0644 "$path"

    sudo tar -xzf "$path" -C /opt

    optPath="$(find /opt -type d -name 'idea-IC-*' | head -n 1)"

    if [ ! -f "$CUSTOM/lib/aliases/jetbrains.aliases.bash" ]; then
        [ -d "$CUSTOM/lib/aliases" ] || { mkdir -p "$CUSTOM/lib/aliases" || exitLog "Unable to create directory '$CUSTOM/lib/aliases'"; }
        cp "$TEMPLATES/aliases.tmpl" "$CUSTOM/lib/aliases/jetbrains.aliases.bash"
    fi

    if ! grep -q "intellij" "$CUSTOM/lib/aliases/jetbrains.aliases.bash"; then
        echo "alias intellij=\"$optPath/bin/idea\"" >> "$CUSTOM/lib/aliases/jetbrains.aliases.bash"
    fi

    alias::enable "jetbrains"; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
intellij-community::remove()
{
    dot::include "alias.functions"

	local result

    optPath="$(find /opt -type d -name 'idea-IC-*' | head -n 1)"

    sed -i "/^.*intellij.*/d" "$CUSTOM/lib/aliases/jetbrains.aliases.bash" &> /dev/null

    sudo rm -rf "$optPath"; result=$?

	return $result
}
