#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# iputils-ping
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A tool to send ICMP echo requests to an ARP address.'
group 'pkgs'
label 'net'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
iputils-ping::check() { dpkg -l | grep iputils-ping 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
iputils-ping::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install iputils-ping &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
iputils-ping::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge iputils-ping &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
