#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# libpam-tmpdir
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
# shellcheck disable=SC2016
about 'Provides more secure $TMPDIR & $TMP for PAM sessions'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
libpam-tmpdir::check() { dpkg -l | grep libpam-tmpdir 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
libpam-tmpdir::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install libpam-tmpdir &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
libpam-tmpdir::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge libpam-tmpdir &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
