#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# libpam-pwquality
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A module which can be plugged into the password stack of a given service to provide strength checking for passwords'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
libpam-pwquality::check() { dpkg -l | grep libpam-pwquality 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
libpam-pwquality::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install libpam-pwquality &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
libpam-pwquality::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge libpam-pwquality &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
