#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# logrotate
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A system which manages the automatic rotation and compression of log files'
group 'pkgs'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
logrotate::check() { dpkg -l | grep logrotate 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
logrotate::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install logrotate &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
logrotate::config()
{
	local result source

    if [ -f "$CUSTOM/cfg/logrotate/logrotate.conf" ]; then
        source="$CUSTOM/cfg/logrotate/logrotate.conf"
    elif [ -f "$DOT_CFG/logrotate/logrotate.conf" ]; then
        source="$DOT_CFG/logrotate/logrotate.conf"
    else
        exitLog "Data file '$DOT_CFG/logrotate/logrotate.conf' not found"
    fi

	sudo cp "$source" /etc/logrotate.conf

    sudo sed -i 's/^#Storage=.*/Storage=persistent/' /etc/systemd/journald.conf
    sudo sed -i 's/^#ForwardToSyslog=.*/ForwardToSyslog=yes/' /etc/systemd/journald.conf
    sudo sed -i 's/^#Compress=.*/Compress=yes/' /etc/systemd/journald.conf

    sudo systemctl restart systemd-journald; result=$?

    sudo sed -i "s/^\$FileCreateMode.*/\$FileCreateMode 0600/g" /etc/rsyslog.conf

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
logrotate::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge logrotate &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
