#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# needrestart
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Checks which daemons need to be restarted after library upgrades'
group 'pkgs'
label 'util'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
needrestart::check() { dpkg -l | grep needrestart 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
needrestart::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install needrestart &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
needrestart::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge needrestart &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
