#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# openssh-server
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'A powerful collection of tools for remotely controlling networked computers and transferring data between them'
group 'pkgs'

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
openssh-server::check() { dpkg -l | grep openssh-server 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
openssh-server::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install openssh-server &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
openssh-server::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge openssh-server &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
