#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# procps
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Provides programs to monitor and halt system processes'
group 'pkgs'
label 'utility'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
procps::check() { dpkg -l | grep procps 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
procps::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install procps &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
procps::remove()
{
	local result

	sudo apt-get -qq -y purge procps &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
