#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# pycharm-community
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'PyCharm-Community - Another top ranking, cross-platform IDE from Jetbrains'
group 'pkgs'
label 'development'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
pycharm-community::check() { sudo find /opt -type d -name 'pycharm-*' &> /dev/null; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
pycharm-community::install()
{
    dot::include "alias.functions" "default-jre"

	local result path optPath dir

    if ! default-jre::check; then pkg::install "default-jre"; fi

    for dir in "${SEARCH_DOWNLOAD[@]}"
    do
        if [ -d "$dir" ]; then
            if find "$dir" -type f | grep -q "pycharm-"; then
                # shellcheck disable=SC2012
                path="$(find "$dir" -name 'pycharm-*' | tail -n 1)"
                break
            fi
        fi
    done

    if [ -z "$path" ]; then
        wget -P "$HOME/Downloads" https://download-cdn.jetbrains.com/python/pycharm-community-2024.2.3.tar.gz
        path="$(find "$HOME/Downloads" -name 'pycharm-*' | tail -n 1)"
    fi

    chmod 0644 "$path"

    sudo tar -xzf "$path" -C /opt

    optPath="$(find /opt -type d -name 'pycharm-*' | tail -n 1)"

    if [ ! -f "$CUSTOM/lib/aliases/jetbrains.aliases.bash" ]; then
        [ -d "$CUSTOM/lib/aliases" ] || { mkdir -p "$CUSTOM/lib/aliases" || exitLog "Unable to create directory '$CUSTOM/lib/aliases'"; }
        cp "$TEMPLATES/aliases.tmpl" "$CUSTOM/lib/aliases/jetbrains.aliases.bash"
    fi

    if ! grep -q "pycharm" "$CUSTOM/lib/aliases/jetbrains.aliases.bash"; then
        echo "alias pycharm=\"$optPath/bin/pycharm\"" >> "$CUSTOM/lib/aliases/jetbrains.aliases.bash"
    fi

    alias::enable "jetbrains"; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
pycharm-community::remove()
{
    dot::include "alias.functions"

	local result

    optPath="$(find /opt -type d -name 'idea-IC-*' | tail -n 1)"

    sed -i "/^.*pycharm.*/d" "$CUSTOM/lib/aliases/jetbrains.aliases.bash" &> /dev/null

    sudo rm -rf "$optPath"; result=$?

	return $result
}
