#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# python
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Interactive high-level object-oriented language'
group 'pkgs'
label 'languages'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
python::check() { dpkg -l | grep python3 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
python::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install python3 python3-pip &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	yes | sudo pip install pythonpy -q -q -q
	yes | sudo pip install tk -q -q -q

	alias::enable python

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
python::remove()
{
	local result gc="${1:-}"

    sudo apt-get -qq -y purge python3-pip &> /dev/null; result=$?
    if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

    sudo pip uninstall -y pythonpy
    sudo pip uninstall -y tk

	alias::disable python

	return $result
}
