#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# rkhunter
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
rkhunter::check() { dpkg -l | grep rkhunter 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
rkhunter::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install rkhunter &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
rkhunter::config()
{
	local result

    sudo sed -i 's/^CRON_DAILY_RUN=.*/CRON_DAILY_RUN="yes"/' /etc/default/rkhunter
    sudo sed -i 's/^APT_AUTOGEN=.*/APT_AUTOGEN="yes"/' /etc/default/rkhunter

    sudo rkhunter --propupd; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
rkhunter::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge rkhunter &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
