#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# shellcheck shell=bash
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A static analysis tool for shell scripts'
group 'pkgs'
label 'development'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
shellcheck::check() { dpkg -l | grep shellcheck 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
shellcheck::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install shellcheck &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
shellcheck::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge shellcheck &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
