#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# software-properties-common
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Provides an abstraction of the used apt repositories'
group 'pkgs'
label 'development'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
software-properties-common::check() { dpkg -l | grep software-properties-common 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
software-properties-common::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install software-properties-common &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
software-properties-common::remove()
{
	local result gc="${1:-}"

    sudo apt-get -qq -y purge software-properties-common &> /dev/null; result=$?
    if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
