#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# sysstat
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'Contains various utilities to monitor system performance and usage activity'
group 'pkgs'

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
sysstat::check() { dpkg -l | grep sysstat 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
sysstat::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install sysstat &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
sysstat::config()
{
	local result

	sudo sed -i '/^ENABLED.*/c\ENABLED="true"' /etc/default/sysstat

    sudo systemctl enable sysstat &> /dev/null
    sudo systemctl start sysstat; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
sysstat::remove()
{
	local result

	sudo apt-get -qq -y purge sysstat &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
