#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# systemd-coredump
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
systemd-coredump::check() { dpkg -l | grep systemd-coredump 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
systemd-coredump::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install systemd-coredump &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
systemd-coredump::config()
{
	local result

    sudo sed -i 's/^#Storage=.*/Storage=none/' /etc/systemd/coredump.conf
    sudo sed -i 's/^#ProcessSizeMax=.*/ProcessSizeMax=0/' /etc/systemd/coredump.conf

    sudo systemctl restart systemd-journald; result=$?

    if [[ $VERBOSE == "Y" ]]; then
        sudo systemctl status systemd-journald --no-pager
        echo
    fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
systemd-coredump::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge systemd-coredump &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
