#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# tcpd
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
tcpd::check() { dpkg -l | grep tcpd 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
tcpd::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install tcpd &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
tcpd::remove()
{
	local result

	  sudo apt-get -qq -y purge tcpd &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
