#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# ufw
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'The Uncomplicated Firewall is an interface to iptables which greatly simplifies the configuration of a firewall'
group 'pkgs'

# ------------------------------------------------------------------
# CHECK
# ------------------------------------------------------------------
ufw::check() { dpkg -l | grep ufw 2> /dev/null 1>&2; return $?; }
# ------------------------------------------------------------------
# INSTALL
# ------------------------------------------------------------------
ufw::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install ufw &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
# ------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------
ufw::config()
{
    local result

    sudo sed -i 's/IPT_SYSCTL=.*/IPT_SYSCTL=\/etc\/sysctl\.conf/' /etc/default/ufw &> /dev/null

    for admin in $FW_ADMIN; do
        sudo ufw allow log from "$admin" to any port "$SSH_PORT" proto tcp &> /dev/null
    done

    sudo ufw allow in on lo &> /dev/null
    sudo ufw allow out on lo &> /dev/null

    sudo ufw deny in from 127.0.0.0/8 &> /dev/null
    sudo ufw deny in from ::1 &> /dev/null

    sudo ufw logging on &> /dev/null

    sudo ufw default deny incoming &> /dev/null

	sudo ufw allow 2376/tcp &> /dev/null        # docker
	sudo ufw allow 7946/udp &> /dev/null
	sudo ufw allow 7946/tcp &> /dev/null
	sudo ufw allow 80/tcp &> /dev/null			# http
	sudo ufw allow 8080/tcp &> /dev/null		# http
	sudo ufw allow 9090/tcp &> /dev/null		# cockpit
	sudo ufw allow 443/tcp &> /dev/null			# https
	sudo ufw allow 2377/tcp &> /dev/null		# docker
	sudo ufw allow 3000/tcp &> /dev/null		# pm2
	sudo ufw allow 3001/tcp &> /dev/null		# pm2

	sudo ufw allow 53/udp &> /dev/null			# dns
	sudo ufw allow 4789/udp &> /dev/null

	sudo ufw allow samba &> /dev/null

	sudo ufw reload &> /dev/null
	sudo ufw --force enable &> /dev/null; result=$?

	return $result
}
# ------------------------------------------------------------------
# REMOVE
# ------------------------------------------------------------------
ufw::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge ufw &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
