#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# unattended-upgrades
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

about 'Ensures that important security patches for installed packages are automatically downloaded'
group 'pkgs'

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
unattended-upgrades::check() { dpkg -l | grep unattended-upgrades 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
unattended-upgrades::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install unattended-upgrades &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
unattended-upgrades::config()
{
	local result

    sudo dpkg-reconfigure -plow unattended-upgrades; result=$?

    return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
unattended-upgrades::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge unattended-upgrades &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
