#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# update-notifier-common
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Daemon which notifies about package updates'
group 'pkgs'
label 'admin'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
update-notifier-common::check() { dpkg -l | grep update-notifier-common 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
update-notifier-common::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install update-notifier-common; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
update-notifier-common::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge update-notifier-common &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
