#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# vlock
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'Virtual Console locking program which helps prevent unauthorised access'
group 'pkgs'
label 'security'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
vlock::check() { dpkg -l | grep vlock 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
vlock::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install vlock; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
vlock::remove()
{
	local result gc="${1:-}"

	  sudo apt-get -qq -y purge vlock &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
