#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# wslu
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A collection of utilities for the Windows Subsystem for Linux (WSL)'
group 'pkgs'
label 'wsl'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
wslu::check() { dpkg -l | grep wslu 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
wslu::install()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y install wslu &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
wslu::remove()
{
	local result gc="${1:-}"

	sudo apt-get -qq -y purge wslu &> /dev/null; result=$?
	if [ -z "$gc" ]; then sudo apt-get -qq -y clean &> /dev/null && sudo apt-get -qq -y autoremove &> /dev/null; fi

	return $result
}
