#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# yq
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A lightweight and portable command-line YAML, JSON, and XML processor'
group 'pkgs'
label 'utility'
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
yq::check() { whereis yq &> /dev/null; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
yq::install()
{
	local result

	sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq

    sudo chmod +x /usr/bin/yq; result=$?

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
yq::remove()
{
	local result

    sudo rm -f /usr/bin/yq; result=$?

	return $result
}
