#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
	if [ ! -d "$HOME/.venv/dotenv" ]; then
		python3 -m venv "$HOME/.venv/dotenv"
	fi
	source "$HOME/.venv/dotenv/bin/activate" && export PATH="$HOME/.venv/dotenv/bin:$PATH"
fi
