#!/usr/bin/env bash
####################################################################
# apt
####################################################################
# Ragdata's Dotfiles - Application Manager
#
# File:         apt
# Author:       Ragdata
# Date:         22/08/2024
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
apt::check() { if command -v apt-transport-https &> /dev/null && command -v apt-listchanges &> /dev/null; then return 0; else return 1; fi }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
apt::install()
{
	local result

	echoInfo "Installing additional packages for 'apt': " -n
	sudo apt-get -qq -y install apt-transport-https apt-listchanges; result=$?
	if [[ "$result" -eq 0 ]]; then echoSuccess "SUCCESS!"; else echoWarning "FAILED!"; fi

	echoInfo "Running garbage collection"
	sudo apt-get -qq -y clean && sudo apt-get -qq -y autoremove
	return $result
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
apt::config()
{
	local result=0

	if [[ ! -f /etc/apt/apt.conf.d/99forve-ipv4 ]]; then
		echoInfo "Configuring 'apt': " -n
		echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4; result=$?
		if [[ "$result" -eq 0 ]]; then echoSuccess "SUCCESS!"; else echoWarning "FAILED!"; fi
	fi

	return $result
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
apt::remove()
{
	local result

	echoInfo "Removing 'apt': " -n
	sudo rm -f /etc/apt/apt.conf.d/99force-ipv4
	sudo apt-get -qq -y purge apt-transport-https apt-listchanges; result=$?
	if [[ "$result" -eq 0 ]]; then echoSuccess "SUCCESS!"; else echoWarning "FAILED!"; fi

	echoInfo "Running garbage collection"
	sudo apt-get -qq -y clean && sudo apt-get -qq -y autoremove
	return $result
}
