#!/usr/bin/env bash
####################################################################
# apt
####################################################################
# Ragdata's Dotfiles - Application Manager
#
# File:         apt
# Author:       Ragdata
# Date:         22/08/2024
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
apt::check() { command -v apt-transport-https &> /dev/null; }

#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
apt::install()
{
	echo "Installing additional packages for 'apt'"
	sudo apt install -y apt-transport-https apt-listchanges || errorExit "FAILURE!"
}

#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
apt::config()
{
	if [[ ! -f /etc/apt/apt.conf.d/99forve-ipv4 ]]; then
		echo "Configuring 'apt'"
		echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4 || errorExit "FAILURE!"
	fi
}

#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
apt::remove()
{
	echo "Removing 'apt'"
	sudo rm -f /etc/apt/apt.conf.d/99force-ipv4
	sudo apt remove --purge apt-transport-https apt-listchanges || errorExit "FAILURE!"
}
