#!/usr/bin/env bash
####################################################################
# dialog
####################################################################
# Ragdata's Dotfiles - Application Manager
#
# File:         dialog
# Author:       Ragdata
# Date:         22/08/2024
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################

#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
dialog::check() { command -v dialog &> /dev/null; }

#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
dialog::install()
{
	echo "Installingd 'dialog'"
	sudo apt install -y dialog
}

#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
dialog::config()
{
	echo "No configuration option for this package"
}

#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
dialog::remove()
{
	echo "Removing 'dialog'"
	sudo apt remove --purge dialog
}
