#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# gh
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2025 Redeyed Technologies
####################################################################
# METADATA
####################################################################
# Name:
# Desc:
# Tags:
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
gh::check() { gh --version &> /dev/null; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
gh::install()
{
	curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
	sudo apt update
	sudo apt install gh -y
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
gh::remove()
{
	sudo apt remove --purge gh -y
}
