#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# logrotate
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2025 Redeyed Technologies
####################################################################
# METADATA
####################################################################
# Name:
# Desc:
# Tags:
####################################################################
# FUNCTIONS
####################################################################
#-------------------------------------------------------------------
# CHECK
#-------------------------------------------------------------------
logrotate::check() { dpkg -l | grep logrotate 2> /dev/null 1>&2; return $?; }
#-------------------------------------------------------------------
# INSTALL
#-------------------------------------------------------------------
logrotate::install()
{
	sudo apt install -qq -y logrotate
}
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
logrotate::config()
{
	local result source

	source="$(checkCustom "$DOT_CFG/logrotate/logrotate.conf")"

	sudo cp "$source" /etc/logrotate.conf

    sudo sed -i 's/^#Storage=.*/Storage=persistent/' /etc/systemd/journald.conf
    sudo sed -i 's/^#ForwardToSyslog=.*/ForwardToSyslog=yes/' /etc/systemd/journald.conf
    sudo sed -i 's/^#Compress=.*/Compress=yes/' /etc/systemd/journald.conf

    sudo systemctl restart systemd-journald; result=$?

    sudo sed -i "s/^\$FileCreateMode.*/\$FileCreateMode 0600/g" /etc/rsyslog.conf
}
#-------------------------------------------------------------------
# REMOVE
#-------------------------------------------------------------------
logrotate::remove()
{
	sudo apt purge -qq -y logrotate
}
#-------------------------------------------------------------------
