# /etc/wsl.conf

[boot]
systemd = true

[automount]
enabled = true
root = /
options = "metadata,uid=1000,gid=1000,umask=22,fmask=11,case=off"
mountFsTab = true

[network]
#hostname = wsl-ubuntu
generateHosts = true
generateResolvConf = false

[interop]
enabled = true
appendWindowsPath = true

[user]
default = ragdata

# [boot]
# command = /boot/wsl-boot.sh -p "192.168.130" -g "192.168.130.1" -i "192.168.130.2" -n "1.1.1.1"
