#!/usr/bin/env bash
####################################################################
# EDITBOX
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
MAN_EDITBOX=$(cat <<manual
"
--editbox filepath height width

The edit-box dialog displays a copy of the file.  You  may  edit
it using the backspace, delete and cursor keys to correct typing
errors.   It  also  recognizes  pageup/pagedown.    Unlike   the
--inputbox,  you  must  tab  to  the 'OK' or 'Cancel' buttons to
close the dialog.  Pressing the 'Enter' key within the box  will
split the corresponding line.

On exit, the contents of the edit window are written to dialog's
output.
"
manual
); export MAN_EDITBOX
# ==================================================================
dotImport "$CFG_DIR"/.dialog-vars
dotImport "$CFG_DIR"/.dialog-edit

$DIALOG --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --clear "$@" \
	--editbox "${DIALOG_INPUT:-$input}" "${HEIGHT:-15}" "${WIDTH:-50}" 2>"$output"
