#!/usr/bin/env bash

if [[ $# != 0 ]]
then
	count=$1
else
	count=10
fi

while [[ $count != 0 ]]
do
	echo "** $count -- $(date)"
	w >&2
	sleep 1
	count=$((count - 1))
	[[ -z "$count" ]] && count=0
done
