#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# compilers
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A server hardening script which restricts compiler access'
group 'scripts'
####################################################################
# FUNCTIONS
####################################################################
script::compilers()
{
    echoLog "[Hardening] Restrict compiler access" -S "▶"

    # shellcheck disable=2046
    while read -r x; do
        if [ -f "$x" ] && [ -x "$x" ]; then
            if ! test -L "$x"; then
                sudo chmod 0750 "$x"
                if [[ $VERBOSE == "Y" ]]; then
                    echo "$x"
                fi
            fi
        fi
    done <<< "$(dpkg-query -L $(dpkg -l | grep compil | awk '{print $2}'))"

    ASCOMP="$(command -v as)"

    # shellcheck disable=2046
    if [ -f "$ASCOMP" ] && [ -x "$ASCOMP" ]; then
        sudo chmod 0750 "$(readlink -eq $(command -v as))"
        if [[ $VERBOSE == "Y" ]]; then
            readlink -eq "$ASCOMP"
        fi
    fi

	return 0
}
