#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# disablefs
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A server hardening script which disables misc, rarely used filesystems'
group 'scripts'
####################################################################
# FUNCTIONS
####################################################################
script::disablefs()
{
    echoLog "[Hardening] Disable misc file systems" -S "▶"

    local FS=() source

    if [ -f "$CUSTOM/cfg/data/.disablefs" ]; then
        source="$CUSTOM/cfg/data/.disablefs"
    elif [ -f "$DOT_CFG/data/.disablefs" ]; then
        source="$DOT_CFG/data/.disablefs"
    else
        exitLog "Data file '$DOT_CFG/data/.disablef' not found"
    fi

    readarray FS < "$source"

    for disable in "${FS[@]}"
    do
        disable="${disable//[$'\t\n\r']}"
        if ! grep -q "$disable" /etc/modprobe.d/disablefs.conf 2> /dev/null; then
            sudo sh -c "echo 'install $disable /bin/true' >> /etc/modprobe.d/disablefs.conf"
        fi
    done

	return 0
}
