#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# fstab
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
#-------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------
script::fstab()
{
    echoLog "Configuring FSTAB" -S "▶"

    if [ -f "$CUSTOM/etc/fstab" ]; then
        source="$CUSTOM/etc/fstab"
    else
        source="$DOT_ETC/fstab"
    fi

    if [ -f "$source" ]; then
        sudo install -b -C -m 0644 -T "$source" /etc/fstab
    fi

	return 0
}
