#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# limits
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A server hardening script which imposes maximum limits on resource use'
group 'scripts'
####################################################################
# FUNCTIONS
####################################################################
script::limits()
{
    echoLog "[Hardening] /etc/security/limits.conf" -S "▶"

    sudo sed -i 's/^# End of file*//' /etc/security/limits.conf
    sudo sh -c "{
        echo '* hard maxlogins 10'
        echo '* hard core 0'
        echo '* soft nproc 512'
        echo '* hard nproc 1024'
        echo '# End of file'
    } >> /etc/security/limits.conf"

    if [[ $VERBOSE == "Y" ]]; then
        grep -v '#' /etc/security/limits.conf | uniq
        echo
    fi

	return 0
}
