#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# rhosts
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A server hardening script for .rhosts'
group 'scripts'
####################################################################
# FUNCTIONS
####################################################################
script::rhosts()
{
    echoLog "[Hardening] .rhosts" -S "▶"

    while read -r hostpasswd
    do
        find "$hostpasswd" \( -name "hosts.equiv" -o -name ".rhosts" \) -exec rm -f {} \; 2> /dev/null
    done <<< "$(awk -F ":" '{print $6}' /etc/passwd)"

    [ -f /etc/hosts.equiv ] && sudo rm -f /etc/hosts.equiv

	return 0
}
