#!/usr/bin/env bash
# shellcheck shell=bash
####################################################################
# sshd
####################################################################
# License:      MIT License
# Repository:	https://github.com/Ragdata/.dotfiles
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
# METADATA
####################################################################
about 'A server hardening script for SSHD'
group 'scripts'
####################################################################
# FUNCTIONS
####################################################################
script::sshd()
{
    echoLog "[Hardening] /etc/ssh/sshd_config" -S "▶"

#    sudo sh -c "awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp"
#    sudo mv /etc/ssh/moduli.tmp /etc/ssh/moduli

    if grep -q '^Include' /etc/ssh/sshd_config; then
        local INCLUDEDIR
        # shellcheck disable=SC2046
        INCLUDEDIR="$(dirname $(grep '^Include' /etc/ssh/sshd_config | awk '{print $NF}'))"

        if [ ! -d "$INCLUDEDIR" ]; then
            sudo mkdir -p "$INCLUDEDIR"
        fi

        SSHDCONF="$INCLUDEDIR/hardening.conf"

        sudo cp /etc/ssh/sshd_config "$SSHDCONF"

        sudo sed -i '/.*Subsystem.*/d' /etc/ssh/sshd_config
        sudo sed -i '/Include.*/d' "$SSHDCONF"
    else
        SSHDCONF=/etc/ssh/sshd_config
    fi

    sudo sed -i '/HostKey.*ssh_host_dsa_key.*/d' "$SSHDCONF"
    sudo sed -i '/KeyRegenerationInterval.*/d' "$SSHDCONF"
    sudo sed -i '/ServerKeyBits.*/d' "$SSHDCONF"
    sudo sed -i '/UseLogin.*/d' "$SSHDCONF"

    sudo sed -i 's/.*X11Forwarding.*/X11Forwarding no/' "$SSHDCONF"
    sudo sed -i 's/.*LoginGraceTime.*/LoginGraceTime 20/' "$SSHDCONF"
    sudo sed -i 's/.*PermitRootLogin.*/PermitRootLogin no/' "$SSHDCONF"
    sudo sed -i 's/.*UsePrivilegeSeparation.*/UsePrivilegeSeparation sandbox/' "$SSHDCONF"
    sudo sed -i 's/.*LogLevel.*/LogLevel VERBOSE/' "$SSHDCONF"
    sudo sed -i 's/.*Banner.*/Banner \/etc\/issue.net/' "$SSHDCONF"
    sudo sed -i 's/.*Subsystem.*sftp.*/Subsystem sftp internal-sftp/' "$SSHDCONF"
    sudo sed -i 's/^#.*Compression.*/Compression no/' "$SSHDCONF"
    sudo sed -i "s/.*Port.*/Port $SSH_PORT/" "$SSHDCONF"

    sudo sh -c "echo '' >> $SSHDCONF"

    if ! grep -q "^LogLevel" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'LogLevel VERBOSE' >> $SSHDCONF"
    fi

    if ! grep -q "^PrintLastLog" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'PrintLastLog yes' >> $SSHDCONF"
    fi

    if ! grep -q "^IgnoreUserKnownHosts" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'IgnoreUserKnownHosts yes' >> $SSHDCONF"
    fi

    if ! grep -q "^PermitEmptyPasswords" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'PermitEmptyPasswords no' >> $SSHDCONF"
    fi

    if ! grep -q "^AllowGroups" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'AllowGroups $SSH_GRPS' >> $SSHDCONF"
    fi

    if ! grep -q "^MaxAuthTries" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'MaxAuthTries 3' >> $SSHDCONF"
    else
        sudo sed -i 's/MaxAuthTries.*/MaxAuthTries 3/' "$SSHDCONF"
    fi

    if ! grep -q "^ClientAliveInterval" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'ClientAliveInterval 200' >> $SSHDCONF"
    fi

    if ! grep -q "^ClientAliveCountMax" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'ClientAliveCountMax 3' >> $SSHDCONF"
    fi

    if ! grep -q "^PermitUserEnvironment" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'PermitUserEnvironment no' >> $SSHDCONF"
    fi

    if ! grep -q "^KexAlgorithms" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256' >> $SSHDCONF"
    fi

    if ! grep -q "^Ciphers" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr' >> $SSHDCONF"
    fi

    if ! grep -q "^Macs" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'Macs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256' >> $SSHDCONF"
    fi

    if ! grep -q "^MaxSessions" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'MaxSessions 3' >> $SSHDCONF"
    else
        sudo sed -i 's/MaxSessions.*/MaxSessions 3/' "$SSHDCONF"
    fi

    if ! grep -q "^UseDNS" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'UseDNS no' >> $SSHDCONF"
    else
        sudo sed -i 's/UseDNS.*/UseDNS no/' "$SSHDCONF"
    fi

    if ! grep -q "^StrictModes" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'StrictModes yes' >> $SSHDCONF"
    else
        sudo sed -i 's/StrictModes.*/StrictModes yes/' "$SSHDCONF"
    fi

    if ! grep -q "^MaxStartups" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'MaxStartups 10:30:60' >> $SSHDCONF"
    else
        sudo sed -i 's/MaxStartups.*/MaxStartups 10:30:60/' "$SSHDCONF"
    fi

    if ! grep -q "^HostbasedAuthentication" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'HostbasedAuthentication no' >> $SSHDCONF"
    else
        sudo sed -i 's/HostbasedAuthentication.*/HostbasedAuthentication no/' "$SSHDCONF"
    fi

    if ! grep -q "^KerberosAuthentication" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'KerberosAuthentication no' >> $SSHDCONF"
    else
        sudo sed -i 's/KerberosAuthentication.*/KerberosAuthentication no/' "$SSHDCONF"
    fi

    if ! grep -q "^GSSAPIAuthentication" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'GSSAPIAuthentication no' >> $SSHDCONF"
    else
        sudo sed -i 's/GSSAPIAuthentication.*/GSSAPIAuthentication no/' "$SSHDCONF"
    fi

    if ! grep -q "^RekeyLimit" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'RekeyLimit 512M 1h' >> $SSHDCONF"
    else
        sudo sed -i 's/RekeyLimit.*/RekeyLimit 512M 1h/' "$SSHDCONF"
    fi

    if ! grep -q "^AllowTcpForwarding" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'AllowTcpForwarding no' >> $SSHDCONF"
    else
        sudo sed -i 's/AllowTcpForwarding.*/AllowTcpForwarding no/' "$SSHDCONF"
    fi

    if ! grep -q "^AllowAgentForwarding" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'AllowAgentForwarding no' >> $SSHDCONF"
    else
        sudo sed -i 's/AllowAgentForwarding.*/AllowTcpForwarding no/' "$SSHDCONF"
    fi

    if ! grep -q "^TCPKeepAlive" "$SSHDCONF" 2> /dev/null; then
        sudo sh -c "echo 'TCPKeepAlive no' >> $SSHDCONF"
    else
        sudo sed -i 's/TCPKeepAlive.*/TCPKeepAlive no/' "$SSHDCONF"
    fi

    sudo cp "$SSHDCONF" "/etc/ssh/sshd_config.$(date +%y%m%d)"
    sudo sh -c "grep -vE '#|^$' \"/etc/ssh/sshd_config.$(date +%y%m%d)\" | sort | uniq > $SSHDCONF"
    sudo rm "/etc/ssh/sshd_config.$(date +%y%m%d)"

    sudo chown root:root "$SSHDCONF"
    sudo chmod 0600 "$SSHDCONF"

    sudo systemctl restart sshd.service

	return 0
}
